import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/shadcn/tooltip";
import { TanstackQueryProvider } from "@/integrations/tanstack-query/provider";
import { Toaster } from "@/components/shadcn/sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ViewTransition } from "react";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={cn("font-sans", inter.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TooltipProvider>
          <TanstackQueryProvider>
            <NuqsAdapter>
              <ViewTransition>{children}</ViewTransition>
            </NuqsAdapter>

            <Toaster />
          </TanstackQueryProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
